# https://taskfile.dev
version: '3'

silent: true

vars:
  TOOLS_DIR:
    sh: echo `pwd`\\bin\\tools
  GO_MODULE: github.com/dxite/chat-service
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "*.gen.go" | tr "\n" " "


  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.10.1
    mvdan.cc/gofumpt@v0.4.0
    github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    - echo "- Format"
    - gofumpt -l -w {{.GO_FILES}}

  lint:
    cmds:
      - echo "- Lint"
      - golangci-lint run -v --fix --timeout=5m ./...

  tests:
    cmds:
      - echo "- Tests"
      - go env -w CGO_ENABLED=1
      - go test -race ./...

  build:
    cmds:
      - echo "- Build"
      - go build ./cmd/chat-service

  tools:
    cmds:
      - echo "- Install dev tools"
      - go env -w "GOBIN={{.TOOLS_DIR}}"
      - for: { var: DEV_TOOLS }
        cmd: go install {{.ITEM}}
      - ls -l "{{.TOOLS_DIR}}"